# Generated by Django 4.2.16 on 2024-12-02 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('noise_level', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Noise Level (dB)')),
                ('total_volume', models.PositiveIntegerField(verbose_name='Total Volume (L)')),
                ('fridge_volume', models.PositiveIntegerField(verbose_name='Fridge Compartment Volume (L)')),
                ('freezer_volume', models.PositiveIntegerField(verbose_name='Freezer Compartment Volume (L)')),
                ('lighting', models.CharField(max_length=255, verbose_name='Fridge Lighting')),
                ('door_shelves', models.PositiveIntegerField(verbose_name='Number of Door Shelves')),
                ('doors', models.PositiveIntegerField(verbose_name='Number of Doors')),
                ('energy_class', models.CharField(max_length=10, verbose_name='Energy Efficiency Class')),
                ('freezer_defrosting', models.CharField(max_length=255, verbose_name='Freezer Defrosting Type')),
                ('refrigerant', models.CharField(max_length=50, verbose_name='Refrigerant')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('weight', models.CharField(max_length=50, verbose_name='Weight (kg)')),
                ('dimensions', models.CharField(max_length=50, verbose_name='Dimensions (WxDxH)')),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('os_version', models.CharField(max_length=50, verbose_name='Operating System Version')),
                ('control_type', models.CharField(max_length=255, verbose_name='Control Type')),
                ('smart_tv_support', models.BooleanField(default=False, verbose_name='Smart TV Support')),
                ('screen_size', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Screen Size (inches)')),
                ('resolution', models.CharField(max_length=50, verbose_name='Screen Resolution')),
                ('refresh_rate', models.PositiveIntegerField(verbose_name='Screen Refresh Rate (Hz)')),
                ('screen_format', models.CharField(max_length=50, verbose_name='Screen Format')),
                ('sound_system', models.CharField(max_length=255, verbose_name='Acoustic System')),
            ],
            bases=('product.product',),
        ),
    ]
