# Generated by Django 4.2.16 on 2024-12-02 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_phone_remove_refrigerator_doors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('laptop_type', models.CharField(default='Ofis', max_length=50, verbose_name='Noutbuk turi')),
                ('os_version', models.CharField(default='Windows', max_length=50, verbose_name='Operatsion tizim')),
                ('display_technology', models.CharField(default='IPS', max_length=50, verbose_name='Displey texnologiyasi')),
                ('display_size', models.DecimalField(decimal_places=1, default=15.6, max_digits=4, verbose_name='Displey diagonali, dyuym')),
                ('screen_resolution', models.CharField(default='1920 x 1080 Full HD', max_length=50, verbose_name='Ekran ruxsati, px')),
                ('processor', models.CharField(default='AMD Ryzen™ 5 7520U', max_length=100, verbose_name='Protsessor')),
                ('cores_count', models.IntegerField(default=4, verbose_name='Yadro soni')),
                ('ram', models.IntegerField(default=8, verbose_name='Operativ xotira (RAM), GB')),
                ('gpu_type', models.CharField(default='integratsiyalashgan', max_length=50, verbose_name='Videokarta turi')),
                ('gpu', models.CharField(default='AMD Radeon Graphics', max_length=100, verbose_name='Videokarta')),
                ('storage_type', models.CharField(default='SDD', max_length=50, verbose_name='Naychali xotira turi')),
                ('ssd_size', models.IntegerField(default=512, verbose_name='SSD xotira hajmi, GB')),
                ('weight', models.DecimalField(decimal_places=2, default=1.59, max_digits=4, verbose_name="Og'irligi, kg")),
            ],
            bases=('product.product',),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Mahsulot haqida batafsil'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/', verbose_name='Mahsulot rasmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aksiya'),
        ),
    ]
