# Generated by Django 4.2.16 on 2024-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_laptop_alter_product_brand_alter_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('wash_type', models.CharField(choices=[('automatic', 'Avtomatik')], default='automatic', max_length=20, verbose_name='Yuvish turi')),
                ('installation', models.CharField(choices=[('built_in', 'O‘rnatilgan')], default='built_in', max_length=20, verbose_name='O‘rnatish turi')),
                ('voltage', models.CharField(default='220 V-240 V', max_length=50, verbose_name='Kuchlanish (V)')),
                ('motor_type', models.CharField(choices=[('inverter', 'Invertorli')], default='inverter', max_length=20, verbose_name='Motor turi')),
                ('loading_type', models.CharField(choices=[('front', 'Oldindan yuklash')], default='front', max_length=20, verbose_name='Yuklash turi')),
                ('max_load', models.IntegerField(default=7, verbose_name='Maksimal yuklash (kg)')),
                ('control_type', models.CharField(choices=[('electronic', 'Elektron boshqaruv')], default='electronic', max_length=20, verbose_name='Boshqaruv turi')),
                ('display', models.BooleanField(default=True, verbose_name='Displey')),
                ('wash_efficiency', models.CharField(default='A+++', max_length=5, verbose_name='Yuvish samaradorligi sinfi')),
                ('max_spin_speed', models.IntegerField(default=1200, verbose_name='Maksimal aylanish tezligi (ob/min)')),
                ('steam_treatment', models.CharField(choices=[('yes', 'Bor'), ('no', 'Yo‘q')], default='yes', max_length=3, verbose_name='Bug bilan ishlov berish')),
                ('color', models.CharField(default='kulrang', max_length=50, verbose_name='Rang')),
            ],
        ),
    ]
