# Generated by Django 4.2.16 on 2024-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_washingmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washingmachine',
            name='control_type',
            field=models.CharField(choices=[('electronic', 'Elektron boshqaruv'), ('mechanical', 'Mexanik boshqaruv'), ('hybrid', 'Gibrid boshqaruv')], default='electronic', max_length=20, verbose_name='Boshqaruv turi'),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='installation',
            field=models.CharField(choices=[('built_in', 'O‘rnatilgan'), ('standalone', 'Mustaqil')], default='built_in', max_length=20, verbose_name='O‘rnatish turi'),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='loading_type',
            field=models.CharField(choices=[('front', 'Oldindan yuklash'), ('top', 'Yuqa yuklash')], default='front', max_length=20, verbose_name='Yuklash turi'),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='motor_type',
            field=models.CharField(choices=[('inverter', 'Invertorli'), ('universal', 'Universal'), ('brush', 'Cho‘tka motori')], default='inverter', max_length=20, verbose_name='Motor turi'),
        ),
        migrations.AlterField(
            model_name='washingmachine',
            name='wash_type',
            field=models.CharField(choices=[('automatic', 'Avtomatik'), ('semi_automatic', 'Yarim avtomatik'), ('manual', 'Qo‘lda boshqariladigan')], default='automatic', max_length=20, verbose_name='Yuvish turi'),
        ),
    ]
